### ISSUE TITLE
Image height

### ISSUE THREAD

**Issue by samantha32123** [tomasgarcia3/oim3690-Term-Poroject#3]
I really enjoy the photos of the different areas on your homepage, they are all the same width but it might appear cleaner if you styled them to all be the same height.

**Comment by tomasgarcia3** [comment]
Thank you for the feedback, Samantha. I previously had one image that was not the same height but I have changed things around so that it looks fun for whoever is visiting my site. I had added javascript to change the image to another place when mouseover and to go back to the original when mouseout.
